Update deploy.yml
Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,10 +54,10 @@ jobs:
       run: |
         echo "Copying zubolaapp to EC2 (excluding test folder)..."
         rsync -avz --no-perms --omit-dir-times --delete \
-          --exclude 'tests' \
+          --exclude '/tests' \
           -e "ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no" \
-          ./zubolaapp/ ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp || echo "Some files were not transferred."
-
+          ./zubolaapp/ ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp || { echo "rsync error occurred"; exit 1; }
+    
     - name: Copy test folder to EC2
       env:
         EC2_HOST: ${{ secrets.EC2_HOST }}
@@ -66,7 +66,8 @@ jobs:
         echo "Copying test folder to EC2..."
         rsync -avz --no-perms --omit-dir-times --delete \
           -e "ssh -i /home/runner/.ssh/aws_key.pem -o StrictHostKeyChecking=no" \
-          ./zubolaapp/tests ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp/tests || echo "Some test files were not transferred."
+          ./zubolaapp/tests ${EC2_USER}@${EC2_HOST}:/home/ec2-user/zubolaapp/tests || { echo "rsync error occurred for tests folder"; exit 1; }
+
 
 
     - name: Verify docker-compose.yml on EC2
